### ISSUE TITLE
Crash on IOS 18

### ISSUE THREAD

**Issue by Olrik-WP** [AlexandreFenyo/iOS-tools#2]
on IOS 18 the application opens then closes immediately

**Comment by AlexandreFenyo** [comment]
Hello Olrik-WP. Many thanks for this report. It was due to a symbol now reserved by iOS: "Trace". I've committed a workaround, renaming Trace to XTrace in the app: https://github.com/AlexandreFenyo/iOS-tools/commit/da9feeb2b50692ca5ef3f693fdab737528d8a547
 It now works correctly on iOS18. Sincerely
